[package]
name = "anomaly"
version = "0.1.0"
authors = ["josario <26515+joxer@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"